- Cargo.lock
- Cargo.toml
hdf5-rust package is not maintained and fails to build on MacOS. Updating to the maintained fork.
See https://github.com/aldanor/hdf5-rust/issues/295
> Use the maintained fork `hdf5-metno` instead of `hdf5`

- Cargo.lock
- Cargo.toml
- rs/index/Cargo.toml
- rs/index/src/hnsw/builder.rs
- rs/index/src/hnsw/index.rs
- rs/index/src/hnsw/reader.rs
- rs/index/src/hnsw/writer.rs
- rs/utils/Cargo.toml
- rs/utils/src/io.rs
HNSW builder store data on disk sequentially by point id. If point_id are close to each other for points that are neighbor with each other we can avoid page cache miss when querying.
> Add reindexer to HNSW builder

- rs/quantization/benches/pq_dist.rs
- rs/quantization/src/pq.rs
- rs/quantization/src/pq_builder.rs
Turns out the streaming distance calculation was not doing any useful work (DCE'd maybe?). Fix it and add unit test.
Updated bm numbers:
```
PQ Distance/pq_distance_128_4_4/Scalar
time:   [99.631 ns 99.922 ns 100.25 ns]
PQ Distance/pq_distance_128_4_4/SIMD
time:   [116.51 ns 116.85 ns 117.27 ns]
PQ Distance/pq_distance_128_4_4/StreamSIMD
time:   [85.223 ns 85.434 ns 85.661 ns]
PQ Distance/pq_distance_128_4_8/Scalar
time:   [104.21 ns 104.43 ns 104.68 ns]
PQ Distance/pq_distance_128_4_8/SIMD
time:   [116.53 ns 116.80 ns 117.14 ns]
PQ Distance/pq_distance_128_4_8/StreamSIMD
time:   [84.768 ns 84.880 ns 85.001 ns]
PQ Distance/pq_distance_128_4_16/Scalar
time:   [104.30 ns 104.42 ns 104.56 ns]
PQ Distance/pq_distance_128_4_16/SIMD
time:   [117.33 ns 117.56 ns 117.81 ns]
PQ …
```
> Fix streaming distance calculation for PQ and add unit test

- Cargo.lock
- Cargo.toml
- rs/index/src/hnsw/builder.rs
- rs/index/src/hnsw/index.rs
- rs/quantization/Cargo.toml
- rs/quantization/benches/pq_dist.rs
- rs/quantization/src/pq.rs
- rs/quantization/src/pq_builder.rs
- rs/quantization/src/quantization.rs
- rs/utils/Cargo.toml
- rs/utils/benches/l2.rs
- rs/utils/src/l2.rs
For completeness
```
L2 Distance/Scalar/16   time:   [3.0676 ns 3.0785 ns 3.0906 ns]
L2 Distance/SIMD/16     time:   [4.5063 ns 4.5171 ns 4.5291 ns]
L2 Distance/Scalar/32   time:   [7.1169 ns 7.1357 ns 7.1607 ns]
L2 Distance/SIMD/32     time:   [6.0645 ns 6.0703 ns 6.0762 ns]
L2 Distance/Scalar/64   time:   [17.253 ns 17.268 ns 17.287 ns]
L2 Distance/SIMD/64     time:   [9.6623 ns 9.6706 ns 9.6802 ns]
L2 Distance/Scalar/128  time:   [46.546 ns 46.596 ns 46.662 ns]
L2 Distance/SIMD/128    time:   [17.162 ns 17.172 ns 17.187 ns]
L2 Distance/Scalar/256  time:   [104.90 ns 105.01 ns 105.15 ns]
L2 Distance/SIMD/256    time:   [33.034 ns 33.049 ns 33.064 ns]
L2 Distance/Scalar/512  time:   [267.97 ns 268.22 ns 268.53 ns]
L2 Distance/SIMD/512    time:   [58.694 ns 58.737 ns 58.791 ns]
L2 …
```
> Benchmark L2 distance

- Cargo.lock
- Cargo.toml
- rs/index/src/hnsw/builder.rs
- rs/index/src/hnsw/reader.rs
- rs/index/src/hnsw/writer.rs
- rs/index_writer/Cargo.toml
- rs/index_writer/src/config.rs
- rs/index_writer/src/index_writer.rs
- rs/index_writer/src/input/hdf5.rs
- rs/index_writer/src/input/mod.rs
- rs/index_writer/src/lib.rs
- rs/index_writer/src/main.rs
- rs/quantization/Cargo.toml
- rs/quantization/benches/pq_dist.rs
- rs/quantization/src/pq.rs
- rs/quantization/src/pq_builder.rs
Only works with 1 input for now.
```
./target/release/index_writer --input-path /home/hieu/Downloads/sift-128-euclidean.hdf5 --output-path /tmp/test_hieu --dataset-name "/train"
[2024-10-31T17:22:19Z INFO  index_writer::index_writer] Start indexing
[2024-10-31T17:22:19Z INFO  index_writer::index_writer] Start training product quantizer
[2024-10-31T17:22:19Z INFO  index_writer::index_writer] Start writing product quantizer
[2024-10-31T17:22:19Z INFO  index_writer::index_writer] Start building index
[2024-10-31T17:23:04Z INFO  index_writer::index_writer] Start writing index
```
```
➜  test_hieu tree .
.
├── hnsw
│   └── index
├── pq_tmp
└── quantizer
├── codebook
└── product_quantizer_config.yaml
4 directories, 3 files
```
> index_writer binary to build an index

- Cargo.lock
- Cargo.toml
- rs/cli/Cargo.toml
- rs/cli/src/main.rs
- rs/index/src/hnsw/index.rs
- rs/index/src/hnsw/reader.rs
- rs/index/src/index.rs
- rs/index_server/Cargo.toml
- rs/index_server/src/index_catalog.rs
- rs/index_server/src/index_manager.rs
- rs/index_server/src/index_provider.rs
- rs/index_server/src/index_server.rs
- rs/index_server/src/main.rs
- rs/quantization/src/pq.rs
IndexServer is up and running!
```
muopdb git:(index-server-manager) env RUST_LOG=info ./target/release/index_server --node-id 0 --index-config-path /mnt/muopdb/indices --index-data-path /mnt/muopdb/data --port 9002
[2024-11-01T21:37:08Z INFO  index_server] Node: 0, listening on port 9002
[2024-11-01T21:37:08Z INFO  index_server::index_manager] New version available: 1
[2024-11-01T21:37:08Z INFO  index_server::index_manager] Fetching index hieu-1
[2024-11-01T21:37:14Z INFO  index_server::index_server] Search result: Some([116631, 94560, 137926, 74676, 972489, 437185, 136880, 411939, 257375, 115555])
muopdb git:(index-server-manager) env RUST_LOG=info ./target/release/cli --port=9002 --node-type=1
[2024-11-01T21:37:14Z INFO  cli] Node type: 1
[2024-11-01T21:37:14Z INFO  cli] Response: …
```
> Index manager for IndexServer

- extra_launch.json
- rs/index/src/hnsw/builder.rs
- rs/index/src/hnsw/index.rs
- rs/index/src/hnsw/utils.rs
- rs/index_writer/src/input/hdf5.rs
RoaringBitmap is much slower than BitVec. But BitVec requires preallocating memory before hand (which is bad if we do it for all queries). Therefore:
* Use `BitVec` for graph builder
* Use `RoaringBitmap` for search query
> Use different context type for graph builder

- rs/quantization/src/lib.rs
- rs/quantization/src/pq.rs
- rs/utils/src/distance/l2.rs
With `StreamingWithSIMDOptimized`, in PQ, we will inline the SIMD calculator. This results in 2x performance improvement in most cases for PQ.
Benchmark:
```
PQ Distance/pq_distance_128_4_4/Scalar
time:   [111.75 ns 111.78 ns 111.82 ns]
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
PQ Distance/pq_distance_128_4_4/SIMD
time:   [213.27 ns 213.38 ns 213.50 ns]
Found 5 outliers among 100 measurements (5.00%)
5 (5.00%) high mild
PQ Distance/pq_distance_128_4_4/StreamingWithSIMD
time:   [95.488 ns 95.529 ns 95.572 ns]
Found 4 outliers among 100 measurements (4.00%)
1 (1.00%) low mild
2 (2.00%) high mild
1 (1.00%) high severe
PQ Distance/pq_distance_128_4_4/StreamingWithSIMDOptimized
time:   [47.953 ns 48.041 ns 48.161 ns]
Found 10 outliers among 100 measurements (10.00%)
2 …
```
> Introduce StreamingWithSIMDOptimized mode for PQ distance calculator

- rs/index/src/ivf/writer.rs
- rs/index/src/posting_list/combined_file.rs
- rs/index/src/posting_list/mod.rs
This will be used in IVF instead of separate centroid storage + posting list storage.
This avoids having to create a fixed centroid storage and a fixed posting list storage by IvfReader when creating an Ivf. Another alternative would be not combining centroid storage and posting list storage in IvfWriter, but minimizing the number of files would be better for performance.
> Introduce fixed centroid + posting list file

- rs/index/src/ivf/builder.rs
- rs/index/src/ivf/index.rs
- rs/index/src/ivf/reader.rs
- rs/index/src/ivf/writer.rs
`num_probes` should not be part of the builder or the index but a parameter to each invocation of `search`
> num_probes should be provided in search

- rs/index/src/ivf/builder.rs
- rs/index_writer/src/index_writer.rs
Repro:
```
$ cargo build --release
$ RUST_LOG=info ./target/release/index_writer --input-path ~/Downloads/sift-128-euclidean.hdf5 --output-path /tmp/test --dataset-name "train" ivf
[2024-11-29T16:28:04Z INFO  index_writer::index_writer] Start indexing (IVF)
[2024-11-29T16:28:04Z INFO  index_writer::index_writer] Start building index
[2024-11-29T16:28:06Z INFO  index_writer::index_writer] Start writing index
$ RUST_LOG=info ./target/release/index_writer --input-path ~/Downloads/sift-128-euclidean.hdf5 --output-path /tmp/test --dataset-name "train" hnsw
[2024-11-29T16:29:14Z INFO  index_writer::index_writer] Start indexing (HNSW)
[2024-11-29T16:29:14Z INFO  index_writer::index_writer] Start training product quantizer
[2024-11-29T16:29:14Z INFO  index_writer::index_writer] Start writing …
```
>  Implement IVF index in index_writer

- rs/index_writer/src/config.rs
- rs/index_writer/src/index_writer.rs
Nothing changes, just move those logics into 2 functions for readability
> Refactor index writer for readability

- Cargo.lock
- Cargo.toml
- rs/index/src/spann/reader.rs
- rs/index_server/Cargo.toml
- rs/index_server/src/index_provider.rs
- rs/index_writer/src/config.rs
- rs/index_writer/src/index_writer.rs
- rs/index_writer/src/scripts/write_index_writer_config.rs
Make the directory better for SPANN:
```
├── base_config.yaml
├── centroids
│   ├── hnsw
│   │   ├── index
│   │   └── vector_storage
│   └── quantizer
│       └── no_op_quantizer_config.yaml
└── ivf
├── index
└── vectors
```
> Fix SPANN reader

- rs/compression/src/elias_fano/ef.rs
- rs/index/src/collection/mod.rs
As titled. This allows multiple reads
> Use RwLock instead of Mutex for versions info

- rs/index_server/src/index_server.rs
- rs/proto/proto/muopdb.proto
- rs/proto/src/muopdb.rs
Add `insert` and `flush` endpoints for `index_server`. This will be used for a quick POC where we will insert and manually flush to create a segment.
> GRPC endpoint for insert and flush

- rs/index/src/ivf/writer.rs
- rs/index/src/spann/builder.rs
- rs/index/src/spann/writer.rs
- rs/index/src/vector/file.rs
This PR introduces 2 optimizations:
* In IVFWriter, when writing vectors, avoid writing to a temporary `FileBackedVectorStorage`
* In `FileBackedVectorStorage`, write the vector directly to `mmap` instead of creating a temporary in-memory buffer
Result (33% improvement):
* Before: indexing takes 45s
* After: indexing takes 31s
> Optimize SPANN & IVF writers

- rs/index/src/ivf/writer.rs
I was trying things out, not needed
> Avoid preallocating large buf writer

- Cargo.lock
- rs/demo/Cargo.toml
- rs/demo/src/main.rs
- rs/index/src/ivf/writer.rs
- rs/index_server/src/index_server.rs
- rs/proto/proto/muopdb.proto
- rs/proto/src/muopdb.rs
Protobuf deserialization takes up 50% of CPU. We don't need it since we deserialize into a contiguous vector anyway
Before
```
[2025-01-01T18:10:55.167Z INFO  insert] Inserted all documents in 16.947639482s
```
After
```
[2025-01-01T18:46:04.902Z INFO  insert] Inserted all documents in 8.948953746s
```
> Introduce insert_binary API to for zero-copy insert

- rs/index/src/ivf/writer.rs
> Encode value 1 by 1 to avoid allocating mem for posting lists

- Cargo.lock
- Cargo.toml
- rs/index/Cargo.toml
- rs/index/src/lib.rs
- rs/index/src/multi_spann/builder.rs
- rs/index/src/multi_spann/mod.rs
- rs/index/src/multi_spann/user_index_info.rs
- rs/index/src/multi_spann/writer.rs
- rs/index/src/segment/mutable_segment.rs
* We're going to have a SPANN index per user. In the writer, we will combine them all into a single file (for each of vector, index). That way we reduce number of files. 
* User index infos will contain the offset and length needed to find the slice of each user's index in the combined files.
> MultiSPANN writer and builder

- rs/index/src/collection/mod.rs
- rs/index/src/multi_spann/writer.rs
- rs/index_server/src/index_server.rs
- rs/proto/proto/muopdb.proto
- rs/proto/src/muopdb.rs
- Add new GRPC endpoint to protobuf definition for getting collection segments
- Add a function in collection module to expose segment names
- Add a function in index_server to implement the endpoint for getting collection segments
Per #225, this is the first step towards manual compaction for segments feature
> Add GRPC endpoint to get segments

- rs/index_server/src/index_server.rs
- rs/proto/proto/muopdb.proto
- rs/proto/src/muopdb.rs
- Add new GRPC endpoint to protobuf definition for compacting collection segments
- Add a function in index_server as placeholder
Per #225, this is the second step towards manual compaction for segments feature
One or more segments don't exist
Less than 2 segments are provided
> GRPC endpoint placeholder for compact segments

- Cargo.lock
- Cargo.toml
- rs/index/Cargo.toml
- rs/index/src/collection/mod.rs
- rs/index/src/collection/reader.rs
- rs/index/src/collection/snapshot.rs
- rs/index/src/lib.rs
- rs/index/src/optimizers/engine.rs
- rs/index/src/optimizers/mod.rs
- rs/index/src/optimizers/noop.rs
- rs/index/src/segment/immutable_segment.rs
- rs/index/src/segment/mod.rs
- rs/index/src/segment/pending_segment.rs
- rs/index_server/src/index_server.rs
- rs/quantization/src/noq/noq.rs
- rs/quantization/src/pq/pq.rs
This builds the framework to hook vacuum and merge optimizer into collection. In this PR, we introduce 2 main classes:
* `PendingSegment` - this will wrap the list of segments currently under optimizing
* `SegmentOptimizer` - this is the trait for vacuum and merge optimizer. Right now we only have `NoopOptimizer` which just duplicates the current inner segment and replace it.
* In `Collection`, we introduce a few more APIs. Caller will call like this
```
let optimizer = NoopOptimizer::new();
let pending_segment = collection.init_optimizing(&segment_names)?;
collection.run_optimizer(&optimizer, &pending_segment)?;
```
> Segment optimizer framework

- rs/index/src/collection/mod.rs
Move the upgradable lock to the point where it's necessary, so we don't block flush
> Minimize lock during optimizing

- rs/index/src/collection/mod.rs
- rs/index/src/collection/reader.rs
- rs/index/src/segment/pending_segment.rs
As tilted. On startup, we clear the pending directory and read anew. 
In the future, once we support deletion, we need to spare the pending deletion list.
> Read pending segment on startup

- rs/config/src/collection.rs
- rs/index/src/collection/mod.rs
- rs/index/src/wal/entry.rs
- rs/index/src/wal/file.rs
- rs/index/src/wal/wal.rs
- rs/index_server/src/index_server.rs
- rs/proto/proto/muopdb.proto
- rs/proto/src/muopdb.rs
Hook WAL into insertion, and default to not using WAL. This option must be selected on collection creation.
> Write into WAL on insertion

- rs/index/src/collection/collection.rs
- rs/index/src/collection/mod.rs
- rs/index/src/collection/reader.rs
- rs/index/src/collection/snapshot.rs
- rs/index/src/optimizers/engine.rs
- rs/index/src/optimizers/mod.rs
- rs/index/src/optimizers/noop.rs
- rs/index/src/segment/mod.rs
- rs/index/src/segment/pending_segment.rs
- rs/index_server/src/collection_catalog.rs
- rs/index_server/src/collection_manager.rs
- rs/index_server/src/collection_provider.rs
- rs/quantization/src/noq/noq.rs
- rs/quantization/src/pq/pq.rs
- rs/utils/src/distance/l2.rs
Previously, Quantizer template stays with segment. However, that means technically we can have multiple types of segments for a collection, which isn't right. This PR moves Quantizer template to collection.
> Move Quantizer template to Collection

- rs/index/src/collection/collection.rs
- rs/index/src/collection/reader.rs
- rs/index/src/lib.rs
- rs/index/src/multi_spann/index.rs
- rs/index/src/optimizers/engine.rs
- rs/index/src/optimizers/merge.rs
- rs/index/src/optimizers/mod.rs
- rs/index/src/optimizers/noop.rs
- rs/index/src/segment/immutable_segment.rs
- rs/index/src/segment/mod.rs
- rs/index/src/segment/pending_segment.rs
- rs/index/src/spann/index.rs
- rs/index/src/spann/iter.rs
- rs/index/src/spann/mod.rs
Merge Optimizer for MuopDB. Note that we only support NoQuantization for merge for now.
With ProductQuantization, we need to store raw vectors in order to rebuild the new segment.
> Implement Merge Optimizer

- rs/index/src/optimizers/merge.rs
- rs/index/src/segment/mod.rs
- rs/index/src/spann/iter.rs
This saves a lot of memory allocation. We have to use manual iteration instead of the `Iterator` trait, since that's very hard to deal with lifetime.
> Avoid copying vector on iteration

- rs/index/src/hnsw/builder.rs
- rs/index/src/hnsw/index.rs
- rs/index/src/hnsw/reader.rs
- rs/index/src/ivf/builder.rs
- rs/index/src/ivf/index.rs
- rs/index/src/ivf/reader.rs
- rs/index/src/ivf/writer.rs
- rs/index/src/multi_spann/builder.rs
- rs/index/src/posting_list/file.rs
- rs/index/src/posting_list/fixed_file.rs
- rs/index/src/posting_list/mod.rs
- rs/index/src/posting_list/storage.rs
- rs/index/src/spann/builder.rs
- rs/index/src/spann/reader.rs
- rs/index/src/spann/writer.rs
- rs/index/src/vector/file.rs
- rs/index/src/vector/fixed_file.rs
- rs/index/src/vector/mod.rs
Use `VectorStorage` instead of the implementations, in preparation for cloud storage
> Stub VectorStorage into IVF and HNSW

- rs/index/src/collection/collection.rs
`try_with_upgraded` will bail on contention
> Fix a small bug where MuopDB refuses to upgrade pending segment

- Cargo.lock
- Cargo.toml
- rs/index_server/Cargo.toml
- rs/index_server/src/main.rs
- rs/index_server/src/metrics.rs
Set up an HTTP server in `index_server` that exposes the `/metrics` endpoint for Prometheus. The current metric is how many requests to the metrics endpoint have been made.
> Expose /metrics endpoint that interacts with Prometheus

- rs/utils/src/lib.rs
Got a warning from compiler. Probably better to use this
> Use standard library ceil_div

- Cargo.lock
- Cargo.toml
- rs/utils/Cargo.toml
- rs/utils/benches/odom.rs
- rs/utils/src/on_disk_ordered_map/map.rs
```
Compiling utils v0.1.0 (/Users/hieu/code/muopdb/rs/utils)
Finished `bench` profile [optimized] target(s) in 0.92s
Running benches/odom.rs (target/release/deps/odom-e013a31eb36dc562)
ODOM/Search/FixedIntegerCodec/16384
time:   [50.373 µs 50.629 µs 50.878 µs]
Found 6 outliers among 100 measurements (6.00%)
4 (4.00%) low mild
2 (2.00%) high mild
ODOM/Search/FixedIntegerCodec/32768
time:   [54.256 µs 54.525 µs 54.802 µs]
Found 5 outliers among 100 measurements (5.00%)
2 (2.00%) low severe
1 (1.00%) low mild
2 (2.00%) high mild
ODOM/Search/FixedIntegerCodec/65536
time:   [69.708 µs 70.052 µs 70.417 µs]
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low severe
2 (2.00%) low mild
2 (2.00%) high mild
2 (2.00%) high severe
ODOM/Search/VarintIntegerCodec/16384
time:   [78.559 µs …
```
> Benchmark for OnDiskOrderedMap

- rs/index/src/ivf/files/invalidated_ids.rs
- rs/index/src/ivf/index.rs
- rs/index/src/multi_spann/index.rs
- rs/index/src/segment/pending_segment.rs
- rs/index/src/spann/index.rs
Using `invalidate_batch`
```
Vacuum/Vacuum/10000     time:   [1.1905 s 1.2054 s 1.2200 s]
```
Not using `invalidate_batch`
```
Vacuum/Vacuum/10000     time:   [3.3587 s 3.3992 s 3.4469 s]
```
> Use invalidate_batch when applying pending deletions

- rs/index/src/wal/file.rs
- rs/index/src/wal/wal.rs
Remove the need for num entries in WAL file. Make it truly append-only. This will be much easier to reason when working on async flush.
> Remove num_entries from WAL file

- rs/index/src/ivf/index.rs
- rs/index/src/multi_spann/index.rs
- rs/index/src/segment/immutable_segment.rs
- rs/index/src/spann/index.rs
The current implementation is very slow and should not be used outside of IVF other for testing
> get_point_id() should only be used for testing

- Cargo.lock
- rs/benchmarks/Cargo.toml
- rs/benchmarks/src/wal_insertion.rs
- rs/index/src/collection/collection.rs
- rs/index/src/wal/file.rs
```
Benchmarking WalInsertion/WalInsertion/1000: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 40.7s.
WalInsertion/WalInsertion/1000
time:   [4.0950 s 4.1411 s 4.1856 s]
change: [+3.4096% +5.0006% +6.4060%] (p = 0.00 < 0.05)
Performance has regressed.
```
> feat: add fsync after WAL writes and create WAL insertion benchmark

- rs/index/src/collection/collection.rs
- rs/index/src/segment/mutable_segment.rs
- rs/index/src/terms/builder.rs
- rs/index/src/tokenizer/tokenizer.rs
- rs/index/src/tokenizer/white_space_tokenizer.rs
- rs/index_server/src/admin_server.rs
- rs/index_server/src/collection_manager.rs
- rs/index_server/src/index_server.rs
- rs/index_server/src/main.rs
This PR refactors the ownership model so that `CollectionManager` completely owns the `CollectionCatalog`. All server components (`IndexServerImpl` and `AdminServerImpl`) now only need to hold an `Arc<RwLock<CollectionManager>>` and access collections through the manager's API. 
This refactor allows multiple threads concurrently read the collection catalog. Previously, the catalog was wrapped in a `Mutex`, which forced all reads and writes to be exclusive and blocked each other.
Now `CollectionManager` is the single point of access for all collection-related operations, resulting in a cleaner and more maintainable architecture.
> perf: let CollectionManager own CollectionCatalog

- rs/benchmarks/src/deletion_and_vacuum.rs
- rs/benchmarks/src/insertion.rs
- rs/benchmarks/src/vacuum.rs
- rs/benchmarks/src/wal_insertion.rs
- rs/config/src/collection.rs
- rs/index/src/collection/core.rs
- rs/index/src/collection/mod.rs
- rs/index/src/collection/reader.rs
- rs/index/src/collection/snapshot.rs
- rs/index/src/ivf/builder.rs
- rs/index/src/optimizers/engine.rs
- rs/index/src/optimizers/merge.rs
- rs/index/src/optimizers/vacuum.rs
- rs/index/src/terms/builder.rs
- rs/index_server/src/collection_catalog.rs
- rs/index_server/src/collection_manager.rs
- rs/index_server/src/index_server.rs
- rs/index_server/src/main.rs
Implemented WAL write groups in Tokio concurrent async context for `Collection::write_to_wal` method, replacing the background thread method. Each group holds a certain number of WAL entries with a fixed upper bound (940 by default). Timeout handling is also handled, in case there are no more `write_to_wal` tasks coming in but the group still waits. Duration till timeout for a group is 100ms. 
Improvement in throughput (performed on MacOS):
```
Benchmarking WalInsertion/WalInsertion/1000: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.0s or enable flat sampling.
WalInsertion/WalInsertion/1000
time:   [109.71 ms 110.19 ms 110.52 ms]
change: [-1.9743% -1.5160% -1.0833%] (p = 0.00 < 0.05)
Performance has improved.
```
> perf: Implement WAL write groups for appending WAL data 
