Cargo.lock, Cargo.toml, rs/index/Cargo.toml, rs/index/src/hnsw_builder.rs, rs/index/src/index.rs, rs/index/src/ivf.rs, rs/index/src/lib.rs, rs/index/src/traverse_state.rs, rs/quantization/src/pq.rs, rs/quantization/src/quantization.rs, rs/utils/Cargo.toml, rs/utils/src/l2.rs, rs/utils/src/lib.rs
It hasn't built anything yet, so the `build` function for HNSW builder is not implemented. Just the logic to add vectors for now.
=> HNSW builder with insert logic

rs/index/src/hnsw_builder.rs, rs/index/src/hnsw_writer.rs, rs/index/src/lib.rs, rs/quantization/src/pq.rs
Persist the graph to disk. Reader on the next PR.
=> Persist HNSW graph to disk

rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/utils.rs
We actually don't need the distance, so I change the interface for this function
=> Simplify get_edges_for_point fn

Cargo.lock, Cargo.toml, rs/quantization/Cargo.toml, rs/quantization/benches/pq_dist.rs
Other implementations of L2 distance (and other types of distance calculators) will be benchmarked with this
=> Add benchmark for PQ distance

rs/utils/src/l2.rs, rs/utils/src/lib.rs
Benchmarking and dynamic selection of L2 distance implementation will be in separate PRs
=> Add SIMD implementation for L2 distance

rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/quantization/benches/pq_dist.rs, rs/quantization/src/pq.rs, rs/quantization/src/quantization.rs
```
PQ Distance/pq_distance_128_4_4/Scalar
time:   [101.01 ns 101.25 ns 101.50 ns]
PQ Distance/pq_distance_128_4_4/SIMD
time:   [116.19 ns 116.35 ns 116.55 ns]
PQ Distance/pq_distance_128_4_4/StreamSIMD
time:   [4.8558 ns 5.0700 ns 5.2823 ns]
PQ Distance/pq_distance_128_4_8/Scalar
time:   [104.44 ns 104.69 ns 104.95 ns]
PQ Distance/pq_distance_128_4_8/SIMD
time:   [116.26 ns 116.42 ns 116.62 ns]
PQ Distance/pq_distance_128_4_8/StreamSIMD
time:   [5.2267 ns 5.4204 ns 5.5919 ns]
PQ Distance/pq_distance_128_4_16/Scalar
time:   [105.09 ns 105.36 ns 105.65 ns]
PQ Distance/pq_distance_128_4_16/SIMD
time:   [116.13 ns 116.32 ns 116.56 ns]
PQ Distance/pq_distance_128_4_16/StreamSIMD
time:   [4.6554 ns 4.8955 ns 5.1570 ns]
PQ Distance/pq_distance_128_8_4/Scalar
time:   [70.116 ns 70.405 ns 70.703 …
```
=> Benchmark PQ distance with streaming distance calculator

rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/reader.rs, rs/index/src/hnsw/writer.rs, rs/index/src/vector/file.rs, rs/index/src/vector/mod.rs, rs/index_writer/src/config.rs, rs/index_writer/src/index_writer.rs, rs/index_writer/src/main.rs
Use this instead of in-memory vector to bound the memory usage
=> Use FileBackedVectorStorage in HNSW builder

rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/reader.rs, rs/index/src/hnsw/writer.rs
=> Read vectors from index in HnswReader

rs/quantization/src/pq.rs
Don't need to compute the same thing every time
=> Small nit to make compute distance very slightly faster

Cargo.lock, Cargo.toml, rs/index/Cargo.toml, rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/utils.rs, rs/index/src/hnsw/writer.rs, rs/index/src/traverse_state.rs
Go from 35s to 25s with this change
=> Optimize graph builder by using bitmap

Cargo.lock, Cargo.toml, rs/index_server/Cargo.toml, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs
No logic yet, just a setup for now
=> Index Server skeleton code

rs/index_writer/src/index_writer.rs, rs/index_writer/src/input/hdf5.rs, rs/index_writer/src/input/mod.rs, rs/utils/src/hdf5_reader.rs, rs/utils/src/main.rs
Add `skip_to` to `Input` to help with the row sampling. Without this API, it will parse all rows (which is really slow)
=> Some small improvements for index_writer

Cargo.lock, rs/aggregator/Cargo.toml, rs/aggregator/src/aggregator.rs, rs/aggregator/src/main.rs, rs/aggregator/src/node_manager.rs, rs/aggregator/src/shard_manager.rs, rs/cli/src/main.rs, rs/index_server/Cargo.toml, rs/index_server/src/index_manager.rs, rs/index_server/src/index_server.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs, rs/utils/src/io.rs
=> Implement aggregator service

rs/index/src/hnsw/index.rs, rs/index/src/hnsw/reader.rs
Refactor the vector mmap to a separate class, so we can instrument statistics later
=> Use fixed-file vector storage for HNSW

rs/aggregator/src/aggregator.rs, rs/cli/src/main.rs, rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/utils.rs, rs/index/src/index.rs, rs/index/src/vector/fixed_file.rs, rs/index_server/src/index_server.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs
Instrument page stats for `SearchContext`. Useful to measure how many pages we access
=> Instrument page stats for SearchContext

Cargo.lock, rs/cli/src/main.rs, rs/index/Cargo.toml, rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/reader.rs, rs/index/src/hnsw/writer.rs, rs/index/src/vector/file.rs, rs/index/src/vector/fixed_file.rs, rs/index/src/vector/mod.rs, rs/index_server/src/index_server.rs, rs/index_writer/Cargo.toml, rs/index_writer/src/config.rs, rs/index_writer/src/hnsw_reindexer.rs, rs/index_writer/src/index_writer.rs, rs/index_writer/src/main.rs
Fix a few bugs with reindex logic, as well as fixed vector logic as well.
=> Experiment reindex

rs/index/src/hnsw/builder.rs
```
No-reindexing: number of pages accessed: 233
Base layer reindexing: number of pages accessed: 53
All layer reindexing: number of pages accessed: 22
```
=> Improve reindexing of HNSW graph for cache locality

rs/index/src/hnsw/builder.rs, rs/index/src/utils.rs
=> Fix reindex tests

rs/index/src/hnsw/writer.rs, rs/utils/src/io.rs
This can be reused by IVF indexing later on
=> Move append_file_to_writer to utils

rs/index/src/ivf/builder.rs, rs/index/src/ivf/index.rs, rs/index/src/vector/file.rs, rs/utils/src/io.rs, rs/utils/src/kmeans/kmeans.rs, rs/utils/src/kmeans/mod.rs, rs/utils/src/lib.rs
Implement [this paper](https://ieeexplore.ieee.org/document/8621917), with Lloyd variant only.
=> Implement Fast Clustering with Flexible Balance Constriants

rs/utils/src/kmeans/kmeans.rs
=> Add tests to kmeans clustering

rs/index/src/ivf/index.rs
=> Revert "Use FixedFileVectorStorage for IVF's dataset"

Cargo.lock, Cargo.toml, rs/index/src/ivf/builder.rs, rs/utils/Cargo.toml, rs/utils/benches/kmeans.rs, rs/utils/src/io.rs, rs/utils/src/kmeans/mod.rs, rs/utils/src/kmeans_builder/kmeans_builder.rs, rs/utils/src/kmeans_builder/mod.rs, rs/utils/src/lib.rs, rs/utils/src/scripts/run_kmeans.rs
10x improvement vs the current non-parallel implementation
=> Parallelize KMeans computation

rs/aggregator/src/node_manager.rs, rs/aggregator/src/shard_manager.rs, rs/index_server/src/index_manager.rs, rs/utils/src/io.rs, rs/utils/src/kmeans_builder/kmeans_builder.rs, rs/utils/src/test_utils.rs
Part of https://github.com/hicder/muopdb/issues/21
=> Chase down unwrap() in utils

Cargo.lock, rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/ivf/index.rs, rs/quantization/benches/pq_dist.rs, rs/quantization/src/pq.rs, rs/quantization/src/pq_builder.rs, rs/quantization/src/quantization.rs, rs/utils/Cargo.toml, rs/utils/benches/l2.rs, rs/utils/src/distance/l2.rs, rs/utils/src/distance/mod.rs, rs/utils/src/kmeans_builder/kmeans_builder.rs, rs/utils/src/lib.rs, rs/utils/src/scripts/run_kmeans.rs
* Some distance calculation optimizations
* Move `l2.rs` to `utils/distance/`
=> Further optimize KMeans calculation

Cargo.lock, rs/cli/Cargo.toml, rs/cli/src/main.rs, rs/utils/src/io.rs, rs/utils/src/scripts/run_kmeans.rs
=> Chase down unwrap() in cli

Cargo.lock, rs/aggregator/Cargo.toml, rs/aggregator/src/aggregator.rs, rs/aggregator/src/main.rs, rs/aggregator/src/node_manager.rs, rs/aggregator/src/shard_manager.rs, rs/proto/build.rs
=> Chase down unwrap() in aggregator

rs/utils/src/distance/l2.rs
16% perf improvement by forcing inline.
=> Inline always some distance calculator

rs/index/src/posting_list/file.rs
We need to adjust the current offset back and forth between current metadata offset and current posting offset (which, for big posting lists, might not be on the same mmap).
=> Fix offset when appending multiple big posting lists

rs/index/src/posting_list/mod.rs
=> Avoid using unsafe when not needed

rs/cli/src/index_viewer.rs, rs/index/src/hnsw/builder.rs, rs/index/src/hnsw/index.rs, rs/index/src/hnsw/reader.rs, rs/index/src/hnsw/utils.rs, rs/index/src/hnsw/writer.rs, rs/index_server/src/index_provider.rs, rs/index_writer/src/hnsw_reindexer.rs, rs/index_writer/src/index_writer.rs, rs/quantization/src/lib.rs, rs/quantization/src/no_op.rs, rs/quantization/src/pq.rs, rs/quantization/src/quantization.rs, rs/quantization/src/typing.rs
Just need 1 type (Quantizer type), and it will infer the types for quantization
=> Make generics less confusing

Cargo.lock, extra_launch.json, rs/index_writer/Cargo.toml, rs/index_writer/src/config.rs, rs/index_writer/src/index_writer.rs, rs/index_writer/src/main.rs, rs/index_writer/src/scripts/write_index_writer_config.rs
I change the command line arguments for `index_writer` to read a yaml config, since we're hitting a large number of config options now
=> Index Writer for HNSW_IVF

rs/index/src/hnsw/reader.rs, rs/index/src/lib.rs, rs/index/src/spann/mod.rs, rs/index_writer/src/index_writer.rs, rs/utils/src/kmeans_builder/kmeans_builder.rs
We add a deterministic seed so that it's not flaky
=> Make kmeans test less flaky

rs/utils/src/kmeans_builder/kmeans_builder.rs
If there is no empty cluster, no need to pick the largest cluster
=> Only handle empty clusters when necessary

rs/index/src/ivf/builder.rs
We also compare the posting list as a way to break ties for `PostingListWithStoppingPoints`. This makes choosing the next top of heap element deterministic (when processing a given stopping point)
=> Complete idx assignment

rs/index/src/ivf/reader.rs, rs/index/src/ivf/writer.rs, rs/index_writer/src/index_writer.rs
Currently we use `NoQuantize`, next PR will handle PQ
=> Introduce quantization to IVF

rs/index/src/hnsw/reader.rs, rs/index/src/ivf/index.rs, rs/index/src/ivf/reader.rs, rs/index/src/ivf/writer.rs, rs/index/src/spann/index.rs, rs/index/src/spann/reader.rs, rs/index_writer/src/index_writer.rs, rs/quantization/src/lib.rs, rs/quantization/src/noq/mod.rs, rs/quantization/src/noq/noq.rs, rs/quantization/src/noq/noq_builder.rs, rs/quantization/src/reader.rs
I'm still working on a way to avoid duplication. Will be done in the next PR. Or in this one if review takes more time than expected.
=> Implement NoQuantizerBuilder

rs/index/src/lib.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/mod.rs
=> Segment trait

Cargo.lock, rs/index/Cargo.toml, rs/index/src/collection/mod.rs, rs/index/src/collection/reader.rs, rs/index/src/collection/snapshot.rs, rs/index/src/lib.rs, rs/index/src/segment/immutable_segment.rs
No tests yet because I don't have a separate writer and builder for SPANN. Will do it next.
=> Use segment in collection

rs/index/src/spann/builder.rs, rs/index/src/spann/index.rs, rs/index/src/spann/mod.rs, rs/index/src/spann/reader.rs, rs/index/src/spann/writer.rs, rs/index_writer/src/index_writer.rs
Have a separate reader and writer logic for SPANN, and use it in index_writer
=> SPANN reader and writer

rs/index/src/collection/mod.rs, rs/index/src/collection/reader.rs
=> Persist TOC for collection

rs/index_server/src/collection_catalog.rs, rs/index_server/src/collection_manager.rs, rs/index_server/src/collection_provider.rs, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs
No functional chanages, just rename
=> Rename index to collection

Cargo.lock, Cargo.toml, py/create_1m_hdf5.py, py/demo_insert_search.py, py/demo_search.py, py/embed_1m_sentences.py, py/generate_1m_sentences.py, py/muopdb_client.py, py/read_hdf5.py, rs/demo/Cargo.toml, rs/demo/src/main.rs, rs/index_server/src/index_server.rs
=> More demo scripts

Cargo.lock, Cargo.toml, rs/demo/Cargo.toml, rs/demo/src/search.rs, rs/index_server/src/index_server.rs
=> Search demo in Rust

rs/index/src/ivf/builder.rs
Cleanup some debugging code I left over earlier
=> Cleanup some debugging code

rs/index_server/src/index_server.rs
I forgot we have this util function
=> Reuse transmute_u8_to_slice

rs/proto/build.rs, rs/proto/src/muopdb.rs
=> Format generated code automatically

rs/utils/benches/dot_product.rs
cargo test and cargo build doesn't build the bench code
=> Fix bench build

rs/aggregator/src/aggregator.rs, rs/cli/src/main.rs, rs/demo/src/main.rs, rs/demo/src/search.rs, rs/index/src/collection/mod.rs, rs/index/src/collection/reader.rs, rs/index/src/collection/snapshot.rs, rs/index/src/hnsw/reader.rs, rs/index/src/index.rs, rs/index/src/ivf/reader.rs, rs/index/src/ivf/writer.rs, rs/index/src/multi_spann/index.rs, rs/index/src/multi_spann/mod.rs, rs/index/src/multi_spann/reader.rs, rs/index/src/multi_spann/user_index_info.rs, rs/index/src/multi_spann/writer.rs, rs/index/src/posting_list/combined_file.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/mutable_segment.rs, rs/index/src/spann/reader.rs, rs/index/src/vector/fixed_file.rs, rs/index_server/src/index_server.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs, rs/utils/src/io.rs
* Reader & index logic for MultiSPANN
* Hook to the rest of the index
=> MultiSPANN reader, index and hook into index_server

py/collection_config.json, py/prepare_muopdb.py
Use this script to bootstrap MuopDB directories.
On root source code directory, run like this:
```
python3 py/prepare_muopdb.py --indices_path=/mnt/muopdb/indices --data_path=/mnt/muopdb/data --collection_name=test-collection-4 --config_path=py/collection_config.json
```
=> Script to prepare directories and create new collection

py/muopdb_pb2.py, py/muopdb_pb2_grpc.py, rs/demo/src/main.rs, rs/index/src/collection/mod.rs, rs/index_server/src/index_server.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs
Just changing the name of the function
=> Change insert_binary to insert_packed

rs/config/src/collection.rs, rs/index/src/multi_spann/writer.rs, rs/index/src/spann/builder.rs
Rename some fields to make it clearer
=> Rename fields in CollectionConfig

rs/index/src/collection/reader.rs, rs/index_server/src/collection_provider.rs
=> Change Reader to CollectionReader for clarity

rs/index/src/ivf/index.rs, rs/index/src/spann/index.rs
=> SPANN test

Cargo.lock, py/muopdb_client.py, py/muopdb_pb2.py, py/muopdb_pb2_grpc.py, rs/config/src/enums.rs, rs/index/src/collection/mod.rs, rs/index_server/Cargo.toml, rs/index_server/src/collection_catalog.rs, rs/index_server/src/collection_manager.rs, rs/index_server/src/collection_provider.rs, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs
We can just create a collection from gRPC
=> Add CreateCollection endpoint

py/muopdb_client.py, py/muopdb_pb2.py, rs/aggregator/src/aggregator.rs, rs/cli/src/main.rs, rs/demo/src/search.rs, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs, rs/proto/proto/muopdb.proto, rs/proto/src/muopdb.rs
=> Change index_name to collection_name

.dockerignore, .github/workflows/rust.yml, Dockerfile, rs/aggregator/src/main.rs, rs/index_server/src/main.rs
Use docker containers for test
=> Use docker as tests

rs/index/src/collection/mod.rs
* Cleanup the `replace_segment` function.
* Only rename version file under write lock. Under read lock, create a version file in a tmp file and rename atomically.
* Add a test that run query and optimizer in different threads
=> Multi-threaded segment optimizer

rs/index/src/collection/mod.rs
Otherwise we will accumulate a lot of pending segments in TOC. It doesn't affect correctness, but it prevents us from cleaning up those.
=> Remove pending segment from TOC after finalizing

rs/index/src/collection/mod.rs
=> Rename some variable names for consistency

rs/index/src/lib.rs, rs/index/src/wal/entry.rs, rs/index/src/wal/file.rs, rs/index/src/wal/mod.rs, rs/index/src/wal/wal.rs
Implementation for the write-ahead-log
=> WAL implementation

rs/index/src/collection/mod.rs, rs/index/src/wal/entry.rs, rs/index/src/wal/file.rs, rs/index/src/wal/wal.rs
We support both insertion and deletion op types
=> Encode WAL op types

rs/index/src/ivf/index.rs
Next step is to add a construction of the invalidated ids set by reading back from invalidated ids storage
=> Add invalidated ids set to IVF

rs/index/src/collection/mod.rs, rs/index/src/segment/mutable_segment.rs, rs/index/src/wal/file.rs, rs/index/src/wal/wal.rs
=> Read WAL on startup

rs/index/src/wal/wal.rs
Add a test to make sure all sequence numbers are covered in WAL
=> Add tests to WAL

rs/config/src/collection.rs, rs/index/src/collection/mod.rs, rs/index/src/segment/mutable_segment.rs, rs/index_server/src/collection_manager.rs, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs, rs/proto/proto/muopdb.proto
Add 2 options to automatically flush mutable segment based on:
* Number of pending operations
* Duration since last flush
=> Automatically flush segments

rs/index/src/optimizers/merge.rs
=> Fix flaky test for merge segments

rs/index/src/collection/collection.rs
=> Fix deadlock in test_collection

rs/index/src/collection/collection.rs, rs/index/src/collection/mod.rs, rs/index/src/multi_spann/index.rs, rs/index/src/optimizers/engine.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/mod.rs, rs/index_server/src/admin_server.rs, rs/index_server/src/index_server.rs, rs/index_server/src/main.rs, rs/proto/build.rs, rs/proto/proto/admin.proto, rs/proto/proto/muopdb.proto, rs/proto/src/lib.rs
=> Add admin endpoint for MuopDB

rs/index/src/collection/collection.rs, rs/index/src/collection/mod.rs, rs/index_server/src/admin_server.rs, rs/index_server/src/index_server.rs, rs/proto/proto/admin.proto, rs/proto/proto/muopdb.proto
Move the segment APIs to admin.proto
=> Cleanup MergeSegments and GetSegments API

rs/aggregator/src/aggregator.rs, rs/aggregator/src/main.rs, rs/cli/src/main.rs, rs/proto/build.rs, rs/proto/proto/aggregator.proto, rs/proto/proto/muopdb.proto, rs/proto/src/lib.rs
Avoid diluting the index server proto for now
=> Move Aggregator to a separate proto

rs/proto/build.rs, rs/proto/src/lib.rs
=> Separate reflection for aggregator

rs/index/src/ivf/index.rs, rs/index/src/vector/fixed_file.rs, rs/index/src/vector/mod.rs
Avoid dynamic dispatch overhead
=> Use batch API in VectorStorage to compute distances

Cargo.lock, Cargo.toml, rs/index/Cargo.toml, rs/index/src/collection/snapshot.rs, rs/index/src/hnsw/index.rs, rs/index/src/ivf/index.rs, rs/index/src/ivf/reader.rs, rs/index/src/multi_spann/index.rs, rs/index/src/multi_spann/reader.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/mod.rs, rs/index/src/segment/pending_segment.rs, rs/index/src/spann/index.rs
Make way for having async vector storage API
=> Asyncify search functions

rs/index/src/ivf/index.rs, rs/index/src/vector/fixed_file.rs, rs/index/src/vector/mod.rs
Change from DashSet to RwLock HashSet for invalidating ID
=> Replace DashSet to Rwlock

rs/index/src/vector/fixed_file.rs
It's better to avoid branches altogether
=> Avoid branch while scanning ids

rs/index/src/optimizers/engine.rs, rs/index/src/optimizers/merge.rs, rs/index/src/optimizers/mod.rs, rs/index/src/optimizers/vacuum.rs
- Create VacuumOptimizer struct
- Implement optimize() function for vacuum optimizer
- Add unit tests
- We want to "vacuum" a segment and avoid waste space storing invalid/deleted docs
- Unit tests:
- Without deleted doc
- With deleted doc
- Without deleted doc for multiple users
- With deleted doc for multiple users
=> Add vacuum optimizer

rs/index/src/ivf/builder.rs
This PR renames variables for clarity
=> [NFC] IVFBuilder should manipulate point_id and not doc_id

rs/index/src/ivf/writer.rs, rs/utils/src/io.rs
Store raw vectors for KMeans
Related issue: https://github.com/hicder/muopdb/issues/416
=> Store raw vectors in addition to quantized vector

rs/index/src/multi_spann/user_index_info.rs, rs/index/src/multi_spann/writer.rs
=> Revert "Feat/save full vectors"

rs/index/src/collection/collection.rs, rs/index/src/hnsw/index.rs, rs/index/src/ivf/index.rs, rs/index/src/multi_spann/index.rs, rs/index/src/multi_spann/reader.rs, rs/index/src/optimizers/merge.rs, rs/index/src/optimizers/vacuum.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/pending_segment.rs, rs/index/src/spann/index.rs, rs/index/src/utils.rs, rs/index_server/src/index_server.rs
=> Change id to doc_id and add some docs

rs/index/src/collection/collection.rs, rs/index/src/collection/snapshot.rs, rs/index/src/multi_spann/index.rs, rs/index/src/multi_spann/reader.rs, rs/index/src/optimizers/merge.rs, rs/index/src/optimizers/vacuum.rs, rs/index/src/segment/immutable_segment.rs, rs/index/src/segment/mod.rs, rs/index/src/segment/pending_segment.rs, rs/index_server/src/index_server.rs
=> Change search_for_ids to search_for_users

rs/index/src/ivf/reader.rs
=> Add test_ivf_reader_read_product_quantizer

rs/utils/src/bloom_filter/bloom_filter.rs
Follow-up PR: Add missing unit test for `double_hash()` overflow handling.
=> Add unit test for Bloom filter combined hashing function

Cargo.lock, Cargo.toml, rs/benchmarks/Cargo.toml, rs/benchmarks/src/insertion.rs
No deletion yet. Will do it in the next PR
=> Basic insertion benchmark

rs/benchmarks/src/insertion.rs
=> Avoid copying vector in bench

Cargo.lock, rs/benchmarks/Cargo.toml, rs/benchmarks/src/deletion_and_vacuum.rs
=> Deletion and Vacuum benchmark

rs/benchmarks/Cargo.toml, rs/benchmarks/src/deletion_and_vacuum.rs, rs/benchmarks/src/vacuum.rs
We can use this to improve the optimizing path
=> Add benchmark for vacuum only

rs/index/src/spann/builder.rs, rs/index/src/spann/index.rs, rs/index/src/spann/iter.rs, rs/index/src/spann/writer.rs, rs/index/src/utils.rs, rs/index/src/vector/file.rs, rs/index/src/vector/fixed_file.rs, rs/index/src/wal/file.rs, rs/index/src/wal/mod.rs, rs/index/src/wal/wal.rs
=> Another rounds of linting

rs/index/src/collection/core.rs
For follower tasks in `write_to_wal`, they should only receives their `seq_no`s when their entries are synced in WAL. That means the leader has to:
1.  append all WAL entries, 
2. sync, 
3. and then send the `seq_no`s to followers
in that order.
Newly measured insertion time in bench (MacOS):
```
Benchmarking WalInsertion/WalInsertion/1000: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.2s or enable flat sampling.
WalInsertion/WalInsertion/1000
time:   [112.26 ms 113.08 ms 113.80 ms]
```
=> fix(write_to_wal): ensure leader syncs before sending seq_no to followers

rs/index/src/lib.rs, rs/index/src/query/iter.rs, rs/index/src/query/iters/ids_iter.rs, rs/index/src/query/iters/mod.rs, rs/index/src/query/iters/term_iter.rs, rs/index/src/query/mod.rs, rs/index/src/query/planner.rs, rs/proto/proto/muopdb.proto
Basic structure so we can start working on hybrid search
=> feat: Basic structure for hybrid search
